# monokai (ish)
array set ::pd_colors {
    dial_background          "#403f34"
    dial_track               "#6b6a5e"
    dial_ticks               "#A9A89E"
    dial_thumb               "#6f9f03"
    dial_thumb_highlight     "#a1d044"
    dial_active              "#a1d044"
    dial_label               "#88846f"
    tooltip_fill             "#56564D"
    tooltip_border           "#6C6C60"
    tooltip_text             "#E7E2B1"
    dial_iolet               "#A3A28F"
    dial_iolet_border        "#A3A28F"

    gop_box 		         "#D8447A"

    canvas_fill 		     "#272822"
    pdwindow_fill 		     "#272822"
    scrollbox_fill           "#272822"
    helpbrowser_fill 	     "#272822"
    text_window_fill 	     "#272822"

    obj_box_text 		     "#A1D044"
    msg_box_text 		     "#D6CC78"
    atom_box_text 		     "#AE81FF"
    atom_box_label 	 	     "#88846f"
    pdwindow_post_text 	     "#CFCFCF"
    helpbrowser_text 	     "#CFCFCF"
    text_window_text 	     "#CFCFCF"
    text                     "#CFCFCF"
    comment 		         "#88846f"

    obj_box_outline 	     "#403f34"
    msg_box_outline 	     "#403f34"
    atom_box_outline 	     "#403f34"
    msg_box_fill 		     "#403f34"
    obj_box_fill 		     "#403f34"
    atom_box_fill 		     "#403f34"

    signal_cord 		     "#D99A53"
    signal_iolet 		     "#D99A53"
    signal_iolet_border      "#D99A53"
    msg_cord 		         "#A3A28F"
    msg_iolet 		         "#A3A28F"
    msg_iolet_border         "#A3A28F"

    graph_outline 		     "#403f34"
    graph_text 		         "#88846f"
    array_name 		         "#AE81FF"
    array_values 		     "#AE81FF"

    obj_box_outline_broken   "#DC5E5E"
    pdwindow_fatal_text 	 "#DC5E5E"
    pdwindow_error_text 	 "#DC5E5E"
    pdwindow_fatal_highlight "#272822"
    pdwindow_debug_text 	 "#A1D044"

    selected 		         "#90BFC9"
    selection_rectangle      "#90BFC9"
    helpbrowser_highlight 	 "#716F5B"
    txt_highlight_front      "#060901"
    text_window_highlight    "#90BFC9"
    txt_highlight 		     "#716F5B"

    text_window_cursor 	     "#FFFFFF"
    canvas_text_cursor 	     "#FFFFFF"
    cursor                   "#FFFFFF"
}